spring:
  datasource:
    url: jdbc:mysql://localhost:3306/to_do_list?useSSL=false
    username: root
    password: Ognaviastralis06
  jpa:
    hibernate:
      ddl-auto: none

someParameter:
  value: 5463