spring:
  datasource:
    url: jdbc:mysql://localhost:3306/to_do_list?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: Ognaviastralis06
  jpa:
    hibernate:
      ddl-auto: update


someParameter:
  value: 5463